// Generated by https://quicktype.io

export interface Members {
  data:       Member[];
  pagination: Pagination;
}

export interface Member {
  id:                number;
  document:          string;
  first_name:        string;
  last_name:         string;
  nick_name?:         string;
  phone:             string;
  cell_phone:        string;
  gender:            string;
  address:           string;
  campus_college:    string;
  electoral_college: string;
  create_date:       Date;
  province:          Location;
  municipality:      Location;
  region:            Location;
  zone:              Location;
  register?:          Register;
}

export interface Location {
  id:   number;
  name: string;
}

export interface Register {
  coordinator_id?:   number;
  coordinator_name?: string;
  editor_id?:        null;
  editor_name?:      null;
}

export interface Pagination {
  total:        number;
  total_pages:  number;
  current_page: number;
  per_page:     number;
}
