// Generated by https://quicktype.io

export interface Users {
  data:       User[];
  pagination: Pagination;
}

export interface User {
  id:           number;
  document:     string;
  first_name:   string;
  last_name:    string;
  email:        string;
  phone:        string;
  address:      string;
  status:       number;
  create_date:  Date;
  role?:        Location | null;
  province?:    Location | null;
  municipality?: Location | null;
  region?:       Location | null;
  zone?:         Location | null;
  distric?:      number | null;
}

export interface Location {
  id?:   number;
  name?: string;
}

export interface Pagination {
  total:        number;
  total_pages:  number;
  current_page: number;
  per_page:     number;
}
