// Generated by https://quicktype.io

export interface Dashboard {
  cards:         Cards;
  region_counts: RegionCounts;
  regions:       Region[];
  zones:         Region[];
  top:           Top[];
  chart:         Chart[];
}

export interface Cards {
  total_members:    number;
  new_month_members: number;
  males:            number;
  female:           number;
}

export interface RegionCounts {
  regions: number;
  zones:   number;
}

export interface Region {
  name:   string;
  total:  number;
  male:   number;
  female: number;
}

export interface Top {
  responsible_name:        string;
  responsible_role:        string;
  coordinator_region_name: null | string;
  total_members:           number;
  male:                    number;
  female:                  number;
}

export interface Chart {
  year:          number;
  month:         number;
  total_members: number;
  male:          number;
  female:        number;
}
